// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate.

export const audioMap = {
  "Hmm, I wonder! If I have 4 plates with 3 cookies on each, how many cookies are there in total?": "assets/audio/audio_hmm_i_wonder_if_i_have_4_plates_with_3_cookies_on_each__0.mp3",
  "What if there's a fast way to add the same number again and again?": "assets/audio/audio_what_if_theres_a_fast_way_to_add_the_same_number_again__1.mp3",
  "Hmm, I wonder! If there are 5 spiders and each spider has 8 legs, how many legs are there altogether?": "assets/audio/audio_hmm_i_wonder_if_there_are_5_spiders_and_each_spider_has_2.mp3",
  "Counting one by one takes so long — is there a quicker way?": "assets/audio/audio_counting_one_by_one_takes_so_long_is_there_a_quicker_wa_3.mp3",
  "Hmm, I wonder! How can equal groups help us count things faster?": "assets/audio/audio_hmm_i_wonder_how_can_equal_groups_help_us_count_things__4.mp3",
  "Equal groups are like teams of the same size!": "assets/audio/audio_equal_groups_are_like_teams_of_the_same_size_5.mp3",
  "Hmm, I wonder! If we know how many groups and how many in each group, can we find the total without counting?": "assets/audio/audio_hmm_i_wonder_if_we_know_how_many_groups_and_how_many_in_6.mp3",
  "Multiplication is just adding the same number again and again!": "assets/audio/audio_multiplication_is_just_adding_the_same_number_again_and_7.mp3",
  "Hmm, I wonder! What happens when we put objects into rows and columns?": "assets/audio/audio_hmm_i_wonder_what_happens_when_we_put_objects_into_rows_8.mp3",
  "That's exactly what an array does!": "assets/audio/audio_thats_exactly_what_an_array_does_9.mp3",
  "Jack picked apples from the orchard. He has 4 baskets, and he puts exactly 3 apples in each basket. Jack wonders... how many apples does he have in total? Let's help Jack!": "assets/audio/audio_jack_picked_apples_from_the_orchard_he_has_4_baskets_an_10.mp3",
  "Each basket has the same number of apples — that means they are equal groups! When groups are equal, we can find the total quickly using multiplication. 4 groups of 3 equals 12! Multiply means groups of the same size!": "assets/audio/audio_each_basket_has_the_same_number_of_apples_that_means_th_11.mp3",
  "Jack drew his baskets in neat rows, like a grid. This is called an array. Each row has 3 apples, and there are 4 rows. The number of groups times the size of each group equals the total! Crack the multiplication code!": "assets/audio/audio_jack_drew_his_baskets_in_neat_rows_like_a_grid_this_is__12.mp3",
  "Jack was so excited! He learned he could use equal groups and arrays to multiply quickly instead of counting one by one. Multiplication — here we come! Your turn now!": "assets/audio/audio_jack_was_so_excited_he_learned_he_could_use_equal_group_13.mp3",
  "Station one — Group and Count! Tap to add baskets and watch the total grow. Each basket has the same number of apples inside. Let's go!": "assets/audio/audio_station_one_group_and_count_tap_to_add_baskets_and_watc_14.mp3",
  "Station two — Array Builder! Look at the equal groups diagram. Find the missing number to complete the multiplication fact. Look carefully!": "assets/audio/audio_station_two_array_builder_look_at_the_equal_groups_diag_15.mp3",
  "Final station — Number Sentence! You will see a multiplication sentence with one blank. Use the number pad to fill it in. You've got this!": "assets/audio/audio_final_station_number_sentence_you_will_see_a_multiplica_16.mp3",
  "The Boss Battle begins! Answer the questions correctly to defeat the boss and claim your Multiplication Master trophy!": "assets/audio/audio_the_boss_battle_begins_answer_the_questions_correctly_t_17.mp3",
  "You defeated the boss! The Golden Multiplication Trophy is yours!": "assets/audio/audio_you_defeated_the_boss_the_golden_multiplication_trophy__18.mp3",
  "Let's explore equal groups and multiplication!": "assets/audio/audio_lets_explore_equal_groups_and_multiplication_19.mp3",
};
